name: GoT_frames
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - IPython
  - graphviz
  - scikit-image=0.15.0
  - pip
  - pip:
     - imageio
     - imageio[pyav]
